const messages = {
  registeredSuccess: { messaege: "You are registered successfully" },
  alreadyRegisteredUser: { messaege: "Already registered" },
  loginSuccess: { messaege: "You are logged in successfully" },
  loginEmailNotRegistered: { messaege: "Email not registered" },
  wrongPass: { messaege: "Password doesnt match" },
  userreq:{message: "Username is required"},
  emailMatch:{message:"Please Enter Valid Format of Email"},
  passMatch:{message:"Please Enter Valid Format of password"},
  emailReq: { messaege: "Email id is required" },
  passReq: { messaege: "Password and newPassword  is required" },
  updatedProfile: { messaege: "Profile successfully updated" },
  userProfiledelete: { messaege: "user Profile successfully deleted" },
  invalidCredentials: { messaege: "Invalid credentials" },
  changePass: { messaege: "Password changed successfully" },
  unAuthorized: { messaege: "You are unauthorized!" },
  routeNotFound: { message: "Route Not Found!" },
  registerSucess: { message: "Registered succesfully" },
  mandatoryFields: { message: "Please add all fields" },
  userNotFound: { message: "User not found" },
  controllerError: { message: 'Conroller Error' },
  validationError: { message: 'validation error' },
  middlewareError: { message: 'middleware error' },
  invalidToken: { message: 'invalid token' },
  tokenVerificationError: { message: 'token verification error' },
  userNameNotValid: { sMessage: 'Only one charecter is capital and others are numbers in username' },
  passwordNotValid: { sMessage: 'at least one capital letter, at least one small letter, at least one symbol, total length 16 in password' },
  userNameNotValidV2: { sMessage: 'all small letter, and one symbol in UserName' },
  passwordNotValidV2: { sMessage: 'at least one capital letter ,at least one symbol, total length 16 in password' },
  authFail: { message: 'Authentication fail' },
  userExists: { sMessage: 'this user already exists' },
  tokenRequire: { sMessage: 'token is require' },
  emailNotValid: { sMessage: 'Please enter a valid email' },
  userNameUpdated: { sMessage: 'userName updated successfully' },
};

module.exports=messages